version: 2.1

orbs:
  win: circleci/windows@5.0

parameters:
  target-ver:
    type: string
    default: "v1.7.10514"
  build-debug:
    type: boolean
    default: true
  save-artifacts:
    type: boolean
    default: true

commands:
  launch_build:
    description: "Launches the build with parameters"
    parameters:
      config:
        type: string
        default: '"Release"'
      platform:
        type: string
        default: '"x86"'
    steps:      
      - run:
          name: Launch the build
          shell: powershell.exe
          command: |
            $MSBuild = "${Env:ProgramFiles}\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe"
            $Config = << parameters.config >>
            $Platform = << parameters.platform >>
            & $MSBuild src\AppInstallerCLI.sln /t:WindowsPackageManager:Rebuild /nologo /nr:false /p:AppxBundlePlatforms="x86" /p:AppxPackageDir="AppxPackages" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=SideloadOnly /p:platform=$Platform /p:configuration=$Config /p:VisualStudioVersion="17.0" /p:SpectreMitigation=false


jobs:
  compile-win-x86-default:
    executor: win/default

    steps:
      - checkout

      - run:
          name: Nuget dependencies
          shell: cmd.exe
          command: nuget restore src\AppInstallerCLI.sln -NonInteractive
          
      - launch_build:
          platform: '"x86"'
          config: '"Release"'

      - when:
          condition: 
            equal: [true, << pipeline.parameters.build-debug >>] 
          steps:
            - launch_build:
                platform: '"x86"'
                config: '"Debug"'

      - run:
            name: List directory result
            shell: cmd.exe
            command: dir /s

      - run:
          name: Create ZIP with component
          shell: bash.exe
          command: |
              .circleci/create_zip.sh << pipeline.parameters.target-ver >>

      - when:
          condition: 
            equal: [true, << pipeline.parameters.save-artifacts >>] 
          steps:
            - store_artifacts:
                path: winget-cli_<< pipeline.parameters.target-ver >>.zip

workflows:
  build-win-x86-default:
    jobs:
      - compile-win-x86-default
